# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Exercise.destroy_all

BODYPARTS = { legs: 0, core: 1, chest: 2, back: 3, shoulders: 4, full: 5 }.freeze
LEVELS = { easy: 0, medium: 1, hard: 2 }.freeze

leg_exercises = [
  { name: "Squats",
    description: "",
    bodypart: BODYPARTS[:legs],
    level: LEVELS[:easy],
    reps_by_level: { 1 => 10, 2 => 15, 3 => 20 }  },
  { name: "Lunges",
    description: "",
    bodypart: BODYPARTS[:legs],
    level: LEVELS[:easy],
    reps_by_level: { 1 => 12, 2 => 16, 3 => 24 }  },
  { name: "Side Lunges",
    description: "",
    bodypart: BODYPARTS[:legs],
    level: LEVELS[:easy],
    reps_by_level: { 1 => 12, 2 => 16, 3 => 24 }  },
  { name: "Deep Squats",
    description: "",
    bodypart: BODYPARTS[:legs],
    level: LEVELS[:medium],
    reps_by_level: { 1 => 8, 2 => 12, 3 => 16 }  },
  { name: "Jump Squats",
    description: "",
    bodypart: BODYPARTS[:legs],
    level: LEVELS[:hard],
    reps_by_level: { 1 => 8, 2 => 12, 3 => 16 } ,
    dynamic: true },
  { name: "Dynamic Lunges",
    description: "",
    bodypart: BODYPARTS[:legs],
    level: LEVELS[:hard],
    reps_by_level: { 1 => 10, 2 => 14, 3 => 18 } ,
    dynamic: true },
  { name: "Star Jumps",
    description: "",
    bodypart: BODYPARTS[:legs],
    level: LEVELS[:hard],
    reps_by_level: { 1 => 8, 2 => 10, 3 => 12 } ,
    dynamic: true }
]

core_exercises = [
  { name: "Crunches",
    description: "",
    bodypart: BODYPARTS[:core],
    level: LEVELS[:easy],
    reps_by_level: { 1 => 12, 2 => 16, 3 => 20 }  },
  { name: "Leg raises",
    description: "",
    bodypart: BODYPARTS[:core],
    level: LEVELS[:meduim],
    reps_by_level: { 1 => 8, 2 => 10, 3 => 14 }  },
  { name: "Plank",
    description: "",
    bodypart: BODYPARTS[:core],
    level: LEVELS[:easy],
    reps_by_level: { 1 => 30, 2 => 60, 3 => 120 }  },
  { name: "Bicycle situps",
    description: "",
    bodypart: BODYPARTS[:core],
    level: LEVELS[:medium],
    reps_by_level: { 1 => 16, 2 => 22, 3 => 30 }  },
  { name: "Jack knife situps",
    description: "",
    bodypart: BODYPARTS[:core],
    level: LEVELS[:medium],
    reps_by_level: { 1 => 10, 2 => 12, 3 => 16 }  },
  { name: "Mountain Climbers",
    description: "",
    bodypart: BODYPARTS[:core],
    level: LEVELS[:medium],
    reps_by_level: { 1 => 20, 2 => 30, 3 => 50 }  },
  { name: "Squat Thrusts",
    description: "",
    bodypart: BODYPARTS[:core],
    level: LEVELS[:hard],
    reps_by_level: { 1 => 8, 2 => 12, 3 => 16 }  }
]

chest_exercises = [
  { name: "Pressup",
    description: "",
    bodypart: BODYPARTS[:chest],
    level: LEVELS[:easy],
    reps_by_level: { 1 => 10, 2 => 14, 3 => 20 } },
  { name: "Narrow Grip Pressup",
    description: "",
    bodypart: BODYPARTS[:chest],
    level: LEVELS[:easy],
    reps_by_level: { 1 => 8, 2 => 10, 3 => 16 } },
  { name: "Shoulder Touch Pressup",
    description: "",
    bodypart: BODYPARTS[:chest],
    level: LEVELS[:medium],
    reps_by_level: { 1 => 10, 2 => 12, 3 => 16 } },
  { name: "Side Twist Pressup",
    description: "",
    bodypart: BODYPARTS[:chest],
    level: LEVELS[:medium],
    reps_by_level: { 1 => 10, 2 => 12, 3 => 16 } },
  { name: "Clap Pressup",
    description: "",
    bodypart: BODYPARTS[:chest],
    level: LEVELS[:hard],
    reps_by_level: { 1 => 10, 2 => 12, 3 => 14 },
    dynamic: true }
]

shoulder_exercises = [
  { name: "Lean Forward Plank Holds",
    description: "",
    bodypart: BODYPARTS[:shoulders],
    level: LEVELS[:easy],
    reps_by_level: { 1 => 20, 2 => 45, 3 => 60 } },
  { name: "Ground and Pound - 1 at a time",
    description: "",
    bodypart: BODYPARTS[:shoulders],
    level: LEVELS[:medium],
    reps_by_level: { 1 => 10, 2 => 12, 3 => 12 } },
  { name: "Ground and Pound - together",
    description: "",
    bodypart: BODYPARTS[:shoulders],
    level: LEVELS[:hard],
    reps_by_level: { 1 => 6, 2 => 8, 3 => 10 } },
  { name: "Air punches",
    description: "",
    bodypart: BODYPARTS[:shoulders],
    level: LEVELS[:easy],
    reps_by_level: { 1 => 30, 2 => 45, 3 => 60 } },
  { name: "Wall Presses",
    description: "",
    bodypart: BODYPARTS[:shoulders],
    level: LEVELS[:easy],
    reps_by_level: { 1 => 12, 2 => 16, 3 => 22 } },
  { name: "Handstand Pressup",
    description: "",
    bodypart: BODYPARTS[:shoulders],
    level: LEVELS[:hard],
    reps_by_level: { 1 => 3, 2 => 5, 3 => 8 } },
  { name: "Dolphin",
    description: "",
    bodypart: BODYPARTS[:shoulders],
    level: LEVELS[:easy],
    reps_by_level: { 1 => 15, 2 => 30, 3 => 60 } },
  { name: "Crow",
    description: "",
    bodypart: BODYPARTS[:shoulders],
    level: LEVELS[:medium],
    reps_by_level: { 1 => 15, 2 => 20, 3 => 30 } }
]

back_exercises = [
  { name: "Back Raises",
    description: "",
    bodypart: BODYPARTS[:back],
    level: LEVELS[:easy],
    reps_by_level: { 1 => 12, 2 => 16, 3 => 25 } },
  { name: "Full Body Raises",
    description: "",
    bodypart: BODYPARTS[:back],
    level: LEVELS[:easy],
    reps_by_level: { 1 => 10, 2 => 12, 3 => 16 } },
  { name: "Swimmers",
    description: "",
    bodypart: BODYPARTS[:back],
    level: LEVELS[:easy],
    reps_by_level: { 1 => 16, 2 => 24, 3 => 30 } },
  { name: "Chin Up",
    description: "",
    bodypart: BODYPARTS[:back],
    level: LEVELS[:medium],
    reps_by_level: { 1 => 6, 2 => 8, 3 => 10 },
    requires_bar: true },
  { name: "Chin Up - Wide Grip",
    description: "",
    bodypart: BODYPARTS[:back],
    level: LEVELS[:hard],
    reps_by_level: { 1 => 6, 2 => 8, 3 => 10 },
    requires_bar: true },
  { name: "Chin Up - Narrow Grip",
    description: "",
    bodypart: BODYPARTS[:back],
    level: LEVELS[:medium],
    reps_by_level: { 1 => 6, 2 => 8, 3 => 10 },
    requires_bar: true }
]

full_body_exercises = [
  { name: "Burpees",
    description: "",
    bodypart: BODYPARTS[:full],
    level: LEVELS[:easy],
    reps_by_level: { 1 => 6, 2 => 8, 3 => 10 } },
  { name: "Burpees - double kickbacks",
    description: "",
    bodypart: BODYPARTS[:full],
    level: LEVELS[:medium],
    reps_by_level: { 1 => 6, 2 => 8, 3 => 10 } },
  { name: "Burpee Jumps",
    description: "",
    bodypart: BODYPARTS[:full],
    level: LEVELS[:medium],
    reps_by_level: { 1 => 6, 2 => 8, 3 => 10 },
    dynamic: true },
  { name: "Burpee Pressup",
    description: "",
    bodypart: BODYPARTS[:full],
    level: LEVELS[:medium],
    reps_by_level: { 1 => 6, 2 => 8, 3 => 10 } },
  { name: "Burpee Pressup Jumps",
    description: "",
    bodypart: BODYPARTS[:full],
    level: LEVELS[:hard],
    reps_by_level: { 1 => 6, 2 => 8, 3 => 10 },
    dynamic: true }
]

Exercise.create(leg_exercises +
                core_exercises +
                shoulder_exercises +
                back_exercises +
                full_body_exercises)
